Update speedtest.py
__builtin__ was changed to builtins in Python 3. I have a error in Python 3.8 and above with Buildozer in Ubuntu Linux 18.04:

 Traceback (most recent call last):
   File "/home/javier/miniconda3/lib/python3.9/site-packages/speedtest.py", line 156, in <module>
     import __builtin__
 ModuleNotFoundError: No module named '__builtin__'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/javier/Descargas/noti1/main.py", line 15, in <module>
     import speedtest
   File "/home/javier/miniconda3/lib/python3.9/site-packages/speedtest.py", line 180, in <module>
     _py3_utf8_stderr = _Py3Utf8Output(sys.stderr)
   File "/home/javier/miniconda3/lib/python3.9/site-packages/speedtest.py", line 166, in __init__
     buf = FileIO(f.fileno(), 'w')
 AttributeError: 'LogFile' object has no attribute 'fileno'

Hope this fixes it, so I can build my APK without errors. Please check it out. Thanks